Repository trimble-oss/modus-icons, pull requests merged in 2023-03, with the labels that each got.

#157 Add Mobile to Components Dropdown on Navbar
  hugo.yml
Labels: skip-changelog

#166 Ship v1.1.0
  .github/workflows/super-linter.yml
  hugo.yml
  icons/modus-solid/folder-unlocked.svg
  package-lock.json
  package.json
Labels: skip-changelog

#167 Remove IE metatag
  docs/layouts/partials/head.html
Labels: 1

#179 Revised some icons & added a few new ones
  app-components/preview/app-components.js
  app-components/src/app/_data/site-data.ts
  docs/assets/js/app-components.js
  icons/modus-outlined/_metadata.json
  icons/modus-outlined/combine.svg
  icons/modus-outlined/delete.svg
  icons/modus-outlined/point-marker-tool.svg
  icons/modus-outlined/polygon-area-tool.svg
  icons/modus-outlined/polygon-concave.svg
  icons/modus-outlined/polygon-cone.svg
  icons/modus-outlined/polygon-drag-rectangle.svg
  icons/modus-outlined/polygon-line-tool.svg
  icons/modus-outlined/polygon-merge.svg
  icons/modus-outlined/polygon-select.svg
  icons/modus-outlined/polygon.svg
  icons/modus-outlined/schema.svg
  icons/modus-outlined/uncombine.svg
  icons/modus-outlined/zoom-box.svg
  icons/modus-solid/_metadata.json
  icons/modus-solid/combine.svg
  icons/modus-solid/delete.svg
  icons/modus-solid/point-marker-tool.svg
  icons/modus-solid/polygon-area-tool.svg
  icons/modus-solid/polygon-concave.svg
  icons/modus-solid/polygon-cone.svg
  icons/modus-solid/polygon-drag-rectangle.svg
  icons/modus-solid/polygon-line-tool.svg
  icons/modus-solid/polygon-merge.svg
  icons/modus-solid/polygon-select.svg
  icons/modus-solid/polygon.svg
  icons/modus-solid/schema.svg
  icons/modus-solid/uncombine.svg
  icons/modus-solid/zoom-box.svg
Labels: 3

#172 Update `.browserslistrc` config for Angular components
  app-components/.browserslistrc
  app-components/preview/app-components.js
  docs/assets/js/app-components.js
Labels: documentation, docs

#183 Added more icons
  app-components/preview/app-components.js
  app-components/src/app/_data/site-data.ts
  docs/assets/js/app-components.js
  icons/modus-outlined/_metadata.json
  icons/modus-outlined/accessibility-circle.svg
  icons/modus-outlined/accessibility.svg
  icons/modus-outlined/delivery-truck-motion.svg
  icons/modus-outlined/delivery-truck.svg
  icons/modus-outlined/drone.svg
  icons/modus-outlined/smiley-dissatisfied-outlined.svg
  icons/modus-outlined/smiley-dissatisfied.svg
  icons/modus-outlined/smiley-neutral-outlined.svg
  icons/modus-outlined/smiley-neutral.svg
  icons/modus-outlined/smiley-satisfied-outlined.svg
  icons/modus-outlined/smiley-satisfied.svg
  icons/modus-outlined/smiley-somewhat-dissatisfied-outlined.svg
  icons/modus-outlined/smiley-somewhat-dissatisfied.svg
  icons/modus-outlined/smiley-somewhat-satisfied-outlined.svg
  icons/modus-outlined/smiley-somewhat-satisfied.svg
  icons/modus-solid/_metadata.json
  icons/modus-solid/accessibility-circle.svg
  icons/modus-solid/accessibility.svg
  icons/modus-solid/delivery-truck-motion.svg
  icons/modus-solid/delivery-truck.svg
  icons/modus-solid/drone.svg
  icons/modus-solid/smiley-dissatisfied-outlined.svg
  icons/modus-solid/smiley-dissatisfied.svg
  icons/modus-solid/smiley-neutral-outlined.svg
  icons/modus-solid/smiley-neutral.svg
  icons/modus-solid/smiley-satisfied-outlined.svg
  icons/modus-solid/smiley-satisfied.svg
  icons/modus-solid/smiley-somewhat-dissatisfied-outlined.svg
  icons/modus-solid/smiley-somewhat-dissatisfied.svg
  icons/modus-solid/smiley-somewhat-satisfied-outlined.svg
  icons/modus-solid/smiley-somewhat-satisfied.svg
Labels: 3

#184 Delete TODO file
  TODO.md
Labels: 1, skip-changelog
