Repository trimble-oss/modus-icons, pull requests merged in 2023-04, with the labels that each got.

#195 Publish npm package to @trimble-oss GitHub registry as well
  .github/workflows/publish-to-npm.yml
Labels: enhancement, 2, github-actions

#197 Updated and added new icons
  .cspell.json
  .github/workflows/azure-static-web-apps-deploy.yml
  app-components/preview/app-components.js
  app-components/src/app/_data/site-data.ts
  docs/assets/js/app-components.js
  icons/modus-outlined/_metadata.json
  icons/modus-outlined/bar-graph-square.svg
  icons/modus-outlined/cube.svg
  icons/modus-outlined/list-numbered.svg
  icons/modus-outlined/polygon-select.svg
  icons/modus-outlined/qr-code.svg
  icons/modus-outlined/text-align-left.svg
  icons/modus-outlined/text-align-right.svg
  icons/modus-outlined/text-bold.svg
  icons/modus-outlined/text-centered.svg
  icons/modus-outlined/text-italic.svg
  icons/modus-outlined/text-strikethrough.svg
  icons/modus-outlined/text-underlined.svg
  icons/modus-solid/_metadata.json
  icons/modus-solid/bar-graph-square.svg
  icons/modus-solid/cube.svg
  icons/modus-solid/list-numbered.svg
  icons/modus-solid/polygon-select.svg
  icons/modus-solid/qr-code.svg
  icons/modus-solid/text-align-left.svg
  icons/modus-solid/text-align-right.svg
  icons/modus-solid/text-bold.svg
  icons/modus-solid/text-centered.svg
  icons/modus-solid/text-italic.svg
  icons/modus-solid/text-strikethrough.svg
  icons/modus-solid/text-underlined.svg
Labels: 3

#202 v1.2.0 - Bump version number for release
  hugo.yml
  package-lock.json
  package.json
Labels: 1, skip-changelog

#203 Update Deploy Script
  .github/workflows/azure-static-web-apps-deploy.yml
Labels: 1
