Repository trimble-oss/modus-icons, pull requests merged in 2023-06, with the labels that each got.

#220 ng update @angular/core@12 @angular/cli@12
  .cspell.json
  app-components/package-lock.json
  app-components/package.json
Labels: documentation, dependencies

#232 Don't include HTML files in npm package
  package-lock.json
  package.json
Labels: bug

#224 Add popover note about SVG class names
  .cspell.json
  docs/assets/scss/_footer.scss
  docs/assets/scss/docs.scss
  docs/layouts/modus-outlined/single.html
  docs/layouts/modus-solid/single.html
  docs/layouts/partials/popover-svg-class-names.html
  docs/layouts/partials/scripts.html
  docs/layouts/transportation/single.html
  postcss.config.js
Labels: docs

#236 Release v1.3.0
  fonts/css.hbs
  hugo.yml
  package-lock.json
  package.json
Labels: 1, skip-changelog

#237 Remove unused Transportation icons
  icons/transportation/envelope.svg
  icons/transportation/export.svg
  icons/transportation/triangle-left.svg
  icons/transportation/triangle-right.svg
Labels: bug, 1

#239 Added 3 icon fixes that were missed
  icons/modus-outlined/cloud-connected.svg
  icons/modus-outlined/cloud-disconnected.svg
  icons/modus-outlined/dashboard.svg
  icons/modus-outlined/file-check-in.svg
  icons/modus-outlined/file-check-out.svg
  icons/modus-outlined/time-off-work.svg
  icons/modus-outlined/toggle-right-panel.svg
  icons/modus-solid/cloud-connected.svg
  icons/modus-solid/cloud-disconnected.svg
  icons/modus-solid/dashboard.svg
  icons/modus-solid/file-check-in.svg
  icons/modus-solid/file-check-out.svg
  icons/modus-solid/time-off-work.svg
  icons/modus-solid/toggle-right-panel.svg
  icons/modus-solid/window-dock-undock.svg
  icons/modus-solid/window-resize.svg
  icons/modus-solid/window-wireframe.svg
  icons/transportation/traffic-historical.svg
Labels: bug, 1

#242 Release v1.3.1
  fonts/css.hbs
  fonts/html.hbs
  hugo.yml
  icons/modus-outlined/_metadata.json
  icons/modus-solid/_metadata.json
  package-lock.json
  package.json
Labels: 1, skip-changelog

#243 Update GitHub Actions & CODEOWNERS
  .cspell.json
  .github/CODEOWNERS
  .github/workflows/mend-security-scan.yml
  .github/workflows/release-notes.yml
  .github/workflows/review-reminder.yml
  .github/workflows/sonar-scan.yml
Labels: bug, 1
